default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  host: <%= ENV['KEKESHI_DATABASE_HOST']%>
  password: <%= ENV["KEKESHI_DATABASE_PASSWORD"]%>
  #database: <%= ENV["KEKESHI_DATABASE_NAME"]%>
  port: 3306
  #timeout: 3600
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: wechat_hook_server_development

test:
  <<: *default
  database: wechat_hook_server_test
  username: root
  host: localhost
  password: root

staging:
  <<: *default
  database: wechat_hook_server_staging
  pool: 25
  username: root
  password: 
  host: 192.168.1.1
  port: 3306

production:
  <<: *default
  database: wechat_hook_server_production